  CREATE TABLE DMS_SAMPLE."SAMPLE_NUMBER_DATA_TYPE" -- 10 TB
   (  
  "COL1_NUMBER_INT" NUMBER, --double precision - AWS SCT
  "COL2_NUMBER_DECIMAL" NUMBER, --double precision - AWS SCT
  "COL3_NUMBER_HIGH_DECIMAL" NUMBER, --double precision - AWS SCT
  "COL4" NUMBER(5,0), -- Integer
  "COL5" NUMBER(12,0), -- Bigint
  "COL6" NUMBER(32,0), -- Numeric
  "COL7" NUMBER(12,2),
  "COL8" NUMBER(24,5),
  "COL9" NUMBER(32,10)
);


INSERT INTO DMS_SAMPLE."SAMPLE_NUMBER_DATA_TYPE"
SELECT ROWNUM,
       ROWNUM / 2,
       ROWNUM * ROWNUM / ( ROWNUM * ROWNUM * ROWNUM * ROWNUM ),
       ROWNUM * 2,
       ROWNUM * ROWNUM * ROWNUM,
       ROWNUM * ROWNUM * ROWNUM * ROWNUM,
       ROWNUM / 2,
       ROWNUM / 3,
       Round(ROWNUM * ROWNUM * ROWNUM / ( ROWNUM * 0.33 ), 10)
FROM   dual
CONNECT BY ROWNUM < 501;
COMMIT;


SELECT * FROM DMS_SAMPLE."SAMPLE_NUMBER_DATA_TYPE";
